= `DEFINE ANALYZER` 语句

在数据库的背景下，分析器在文本处理和搜索中扮演着至关重要的角色。它由其名称、一组分词器和一系列过滤器定义。

可以使用 xref:functions/database/search.adoc#searchhighlight[search::analyze()] 函数来测试分析器的输出。

== 要求

* 在使用 `DEFINE ANALYZER` 语句之前，您必须以root用户、命名空间用户或数据库用户的身份进行身份验证。
* 在使用 `DEFINE ANALYZER` 语句之前，xref:statements/use.adoc[您必须选择您的命名空间和数据库]。

== 语句语法

.SurrealQL语法
[source,sql]
----
DEFINE ANALYZER [ OVERWRITE | IF NOT EXISTS ] @name [ TOKENIZERS @tokenizers ] [ FILTERS @filters ] [ COMMENT @string ]
----

== 分词器

分词器负责根据一组指令将给定的文本分解成单独的标记。在定义分析器时，可以使用几种分词器，如下所示：

=== `blank`

空白分词器通过在遇到空格、制表符或换行字符时创建一个新的标记，将文本分解成标记。这是一种直接的方法，根据空白字符将文本分割成单词或块。

[source,sql]
----
DEFINE ANALYZER example_blank TOKENIZERS blank;
search::analyze("example_blank", "hello world");
----

.输出
[source,sql]
----
[
	'hello',
	'world'
]
----

=== `camel`

驼峰分词器用于识别并创建标记，当文本中的下一个字符是大写时。这对于处理驼峰命名法或帕斯卡命名法的文本特别有用，常见于编程中，将它们分割成有意义的单词。

[source,sql]
----
DEFINE ANALYZER example_camel TOKENIZERS camel;
search::analyze("example_camel", "helloWorld");
----

.输出
[source,sql]
----
[
	'hello',
	'World'
]
----

=== `class`

类分词器通过检测字符的Unicode类别的变化（数字、字母、标点、空白）将文本分割成标记。当字符类别变化时，它创建一个新的标记，区分数字、字母、标点和空白。这允许根据字符类型灵活分词。

[source,sql]
----
DEFINE ANALYZER example_class TOKENIZERS class;
search::analyze("example_class", "123abc!XYZ");
----

.输出
[source,sql]
----
[
	'123',
	'abc',
	'!',
	'XYZ'
]
----

=== `punct`

标点分词器通过在遇到标点字符时分割文本来生成标记。它适用于根据标点符号对句子进行分词或将文本分解成更小的单元。

[source,sql]
----
DEFINE ANALYZER example_punct TOKENIZERS punct;
search::analyze("example_punct", "Hello, World!");
----

.输出
[source,sql]
----
[
	'Hello',
	',',
	'World',
	'!'
]
----

== 过滤器

过滤器负责将这些标记转换以进行进一步的处理和分析。

=== `ascii`

ASCII过滤器负责通过替换或删除文本中的变音标记（重音和特殊字符）来处理标记。它通过将带重音的字符转换为它们的基本ASCII等价物来帮助标准化文本，使其更适合各种文本分析任务。

[source,sql]
----
DEFINE ANALYZER example_ascii TOKENIZERS class FILTERS ascii;
search::analyze("example_ascii", "résumé café");
----

.输出
[source,sql]
----
[
	'resume',
	'cafe'
]
----

=== `lowercase`

小写过滤器将标记转换为小写，确保文本一致地以小写格式存在。这通常用于使文本对搜索和分析目的不区分大小写。

[source,sql]
----
DEFINE ANALYZER example_lowercase TOKENIZERS class FILTERS lowercase;
search::analyze("example_lowercase", "Hello World");
----

.输出
[source,sql]
----
[
	'hello',
	'world'
]
----

=== `uppercase`

大写过滤器将标记转换为大写，确保文本以大写格式保持一致。当特定分析或搜索操作需要不区分大小写时，它可能会很有用。

例如，如果您有文本 *“Hello World”*，大写过滤器将创建两个标记，*[“HELLO”，“WORLD”]*。以下是如何使用大写过滤器的示例：

[source,sql]
----
DEFINE ANALYZER example_uppercase TOKENIZERS class FILTERS uppercase;
search::analyze("example_uppercase", "Hello World");
----

.输出
[source,sql]
----
[
	'HELLO',
	'WORLD'
]
----

=== `edgengram(min,max)`

边缘ngram过滤器用于创建代表术语前缀的标记。它生成一系列逐渐构建术语的标记，这对于自动完成或基于部分单词的搜索很有用。它接受两个参数 `min` 和 `max`，定义前缀中的最小和最大字符数。

例如，如果您有文本 *“apple banana”*，边缘ngram过滤器将创建六个标记，*[“a”，“ap”，“app”，“b”，“ba”，“ban”]*。以下是如何使用边缘ngram过滤器的示例：

[source,sql]
----
DEFINE ANALYZER example_edgengram TOKENIZERS class FILTERS edgengram(1,3);
search::analyze("example_edgengram", "apple banana");
----

[source,sql]
----
[
	'a',
	'ap',
	'app',
	'b',
	'ba',
	'ban'
]

----

=== `ngram(min,max)`

ngram过滤器用于从给定的文本或语音样本中创建一系列‘n’标记。这些项目可以是音节、字母、单词或碱基对，具体取决于应用。它接受两个参数 `min` 和 `max`，表示您希望从min大小开始创建n-gram。

[source,sql]
----
DEFINE ANALYZER example_ngram TOKENIZERS class FILTERS ngram(1,3);
search::analyze("example_ngram", "apple banana");
----

.输出
[source,sql]
----
[
	'a',
	'ap',
	'app',
	'p',
	'pp',
	'ppl',
	'p',
	'pl',
	'ple',
	'l',
	'le',
	'e',
	'b',
	'ba',
	'ban',
	'a',
	'an',
	'ana',
	'n',
	'na',
	'nan',
	'a',
	'an',
	'ana',
	'n',
	'na',
	'a'
]
----

=== `snowball(language)`

雪球过滤器对标记应用Snowball词干提取，将它们简化为根形式，并转换为小写。以下支持的语言可以作为snowball的参数传递：阿拉伯语、丹麦语、荷兰语、英语、法语、德语、希腊语、匈牙利语、意大利语、挪威语、葡萄牙语、罗马尼亚语、俄语、西班牙语、瑞典语、泰米尔语、土耳其语。

[source,sql]
----
DEFINE ANALYZER english_snowball TOKENIZERS class FILTERS snowball(english);
DEFINE ANALYZER german_snowball TOKENIZERS class FILTERS snowball(german);

RETURN [
    search::analyze("english_snowball", "Looking at some running cats"),
    search::analyze("german_snowball", "Sollen wir was trinken gehen?")
];
----

.输出
[source,sql]
----
[
	[
		'look',
		'at',
		'some',
		'run',
		'cat'
	],
	[
		'soll',
		'wir',
		'was',
		'trink',
		'geh',
		'?'
	]
]
----

[[using-if-not-exists-clause]]
== 使用 `IF NOT EXISTS` 子句

IF NOT EXISTS子句可以用来定义一个分析器，只有在它尚未存在时才定义。如果您想确保只有在分析器尚未存在时才创建分析器，应该在使用SurrealDB定义分析器时使用IF NOT EXISTS子句。如果分析器已经存在，DEFINE USER语句将返回一个错误。

当您想要安全地尝试定义一个分析器而不手动检查其存在时，它特别有用。

另一方面，当您想要确保无论分析器是否已经存在，都要更新分析器定义时，您不应该使用IF NOT EXISTS子句。在这种情况下，您可能更喜欢使用OVERWRITE子句，它允许您定义一个分析器并覆盖一个已经存在的分析器，确保总是使用分析器定义的最新版本。

OVERWRITE子句可以用来创建一个分析器并覆盖一个已经存在的分析器。当您想要修改现有的分析器定义时，应该使用OVERWRITE子句。如果分析器已经存在，DEFINE ANALYZER语句将用新的分析器定义覆盖现有的分析器定义。

有关将分析器应用于索引的示例，可以在DEFINE INDEX语句的文档中找到。

这个示例创建了一个基于字符类别对文本进行分词，然后对标记应用小写过滤器的分析器。

这个示例创建了一个专门处理英文文本的分析器。

这个示例创建了一个专门用于自动完成任务的分析器。

这个示例创建了一个专门用于源代码分析的分析器。
